### ISSUE TITLE
Reflector doesn't get table for N-N relations

### ISSUE THREAD

**Issue by schealex** [spiritix/lada-cache#1]
Hey there,

first of all, very great package! but i've got a problem having a user and group model
where group has users() and user has groups() many-to-many relation.
for some reason if i update the relation from user model everything is fine. but if i update from group model the old relations stay cached and won't show.

any idea on why that is?
i'm pretty new to laravel and couldn't fine the hook u use to detect and flush cache on using attach() or detach() where are those located?

[EDIT] this is what i do for the update:

```
                $group->display_name = Input::get('display_name');
                $group->description = Input::get('description');
                $group->save();

                // remove all existing users and set only checked
                if (\Auth::User()->can('group-assign-user')) {
                    $group->users()->detach();
                    $new_users = (Array)Input::get('users');
                    foreach ($new_users as $user) {
                        $group->users()->attach($user);
                    }
                }
```

**Comment by spiritix** [comment]
Hi, thank you. I am going to refactor the package in the next weeks and release 2.0 ASAP. It will contain some new features as well as bug fixes. 

The problem is probably, that the reflector doesn't get the N-N table from the query builder. I will fix this in the next release.

The model observers which are fired on delete or update are here:
https://github.com/spiritix/lada-cache/blob/master/src/Spiritix/LadaCache/Database/Model.php#L38-L56

**Comment by schealex** [comment]
yeah got that by now i guess there needs to be additional observers for attach() and detach()?!
thanks for the great work, let me know if i can help you out to get 2.0 even faster :)
i'm quite new to laravel but otherwise a kinda good programmer.
keep up the good work on this package!

**Comment by spiritix** [comment]
There is no attach or detach event. The detach method is firing the delete event, so this should work.
Sure, feel free to submit a pull request for this bug!

**Comment by schealex** [comment]
i'm not feeling comfortable enough with laravel to resolve this bug i'm afraid. but looking forward to the fix!

**Comment by spiritix** [comment]
Solved in v.1.1
