### ISSUE TITLE
Support for Laravel 8

### ISSUE THREAD

**Issue by abishekrsrikaanth** [spiritix/lada-cache#101]
Can you please add support for Laravel 8

**Comment by spiritix** [comment]
It's very likely that the library will work with Laravel 8 already (use v.5.x). Official support is on the roadmap, however I currently don't have any capacity to work on that. Contributions are appreciated.

**Comment by spiritix** [comment]
Just saw that someone is working on it already: https://github.com/spiritix/lada-cache/pull/100
