### ISSUE TITLE
PHP 8.0 error call_user_func_array 🐛 

### ISSUE THREAD

**Issue by gieroj** [spiritix/lada-cache#102]
Hi It's not working correctly with PHP 8.0

Unknown named parameter $builder {"exception":"[object] (Error(code: 0): Unknown named parameter $builder at /project/vendor/spiritix/lada-cache/src/Spiritix/LadaCache/Reflector.php:237)

It's about call_user_func_array() function

**Comment by spiritix** [comment]
Fixed in https://github.com/spiritix/lada-cache/releases/tag/v5.1.1
