### ISSUE TITLE
Too few arguments

### ISSUE THREAD

**Issue by bytestream** [spiritix/lada-cache#104]
Relates to https://github.com/spiritix/lada-cache/issues/103

The `Database/Connection.php` class provides 4 arguments to `Database/QueryBuilder.php`

https://github.com/spiritix/lada-cache/blob/1b345dbc0940f150d1c49f6ce15570102abbeff6/src/Spiritix/LadaCache/Database/Connection.php#L31

`Database/QueryBuilder.php` expects 5 arguments.

https://github.com/spiritix/lada-cache/blob/1b345dbc0940f150d1c49f6ce15570102abbeff6/src/Spiritix/LadaCache/Database/QueryBuilder.php#L53

This results in the PHP error shown in the linked issue.

I do not believe this is intended? PHPStan would pick up this error. For example:
```
 ------ --------------------------------------------------------------------------------------------------- 
  Line   Spiritix/LadaCache/Database/Connection.php                                                         
 ------ --------------------------------------------------------------------------------------------------- 
  31     Class Spiritix\LadaCache\Database\QueryBuilder constructor invoked with 4 parameters, 5 required.  
 ------ ---------------------------------------------------------------------------------------------------
```

You can replicate the issue by registering the service provider but not adding the trait to a model.

**Comment by genesiscz** [comment]
Basically duplicate: https://github.com/spiritix/lada-cache/issues/91

**Comment by spiritix** [comment]
Which version of Laravel and Lada Cache are you guys using?

**Comment by bytestream** [comment]
@spiritix I tested it on Lada Cache v5.1.1 and Laravel 6.20.x (latest versions at the time of opening)

**Comment by genesiscz** [comment]
New one. Basically anything that uses query method on Connection has to fail, because you don't pass the required argument, model: 

https://github.com/spiritix/lada-cache/blob/master/src/Spiritix/LadaCache/Database/Connection.php#L31
https://github.com/spiritix/lada-cache/blob/master/src/Spiritix/LadaCache/Database/QueryBuilder.php#L58

**Comment by spiritix** [comment]
Should be fixed with the latest release
