### ISSUE TITLE
Spatie permission used with Lada-cache

### ISSUE THREAD

**Issue by Archana-Soni** [spiritix/lada-cache#108]
Hi.

I am using version like 

laravel/framework - 5.8.*
spatie/laravel-permission - ^2.9
spiritix/lada-cache - ^3.0

using this if i am trying to do like in my controller 

    $user = Auth::user();
    $companyId = $user->company_id;
    return response()->json(
      User::where('company_id', $companyId)->
      role('portal_admin')->
      with('company')->
      with('roles')->
      with('permissions')->
      orderBy('company_id', 'asc')->
      orderBy('first_name', 'asc')->
      simplePaginate(50)
    );
then will get error like

exception: "Symfony\\Component\\Debug\\Exception\\FatalThrowableError"
file: "D:\\G4\\htdocs\\g4-logistics-portal\\vendor\\spiritix\\lada-cache\\src\\Spiritix\\LadaCache\\Reflector.php"
line: 126
message: "Argument 1 passed to Spiritix\\LadaCache\\Reflector::getTablesFromWhere() must be an instance of Spiritix\\LadaCache\\Database\\QueryBuilder, instance of Illuminate\\Database\\Query\\Builder given, called in D:\\G4\\htdocs\\g4-logistics-portal\\vendor\\spiritix\\lada-cache\\src\\Spiritix\\LadaCache\\Reflector.php on line 145

so please help me on this

**Comment by spiritix** [comment]
Unfortunately, I can't provide support for outdated versions any more. Please upgrade to the current version.
