### ISSUE TITLE
Use many unions and use paginate errors

### ISSUE THREAD

**Issue by nguyendachuy** [spiritix/lada-cache#110]
Hello

When I use many unions with the use of paginate, error occurs

Error appears when I set **LADA_CACHE_ACTIVE = true**
Also it works well when not using LADA

Here is code
`$a->union($b)->union($c)->paginate(10);`

**Error**: **Undefined property: stdClass::$aggregate**

```
"Undefined property: stdClass::$aggregate"

"\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php"
2198
array:2 [▼
  "columns" => array:1 [▼
    0 => "*"
  ]
  "results" => array:1 [▼
    0 => {#2051}
  ]
]
```

Version: 3.*
Laravel: 5.8

Thanks for reading!

**Comment by spiritix** [comment]
Sorry for the late reply. I don't provide support for older versions of Lada Cache anymore. Please upgrade to the most recent version.
