### ISSUE TITLE
Getting lada-cache error

### ISSUE THREAD

**Issue by dipam68** [spiritix/lada-cache#111]
exception: "Symfony\\Component\\Debug\\Exception\\FatalThrowableError"
file: "/var/www/html/project-name/vendor/spiritix/lada-cache/src/Spiritix/LadaCache/Reflector.php"
line: 126
message: "Argument 1 passed to Spiritix\\LadaCache\\Reflector::getTablesFromWhere() must be an instance of Spiritix\\LadaCache\\Database\\QueryBuilder, instance of Illuminate\\Database\\Query\\Builder given, called in /var/www/html/project-name/vendor/spiritix/lada-cache/src/Spiritix/LadaCache/Reflector.php on line 145"

Package Information : 
"php": ">=7.2",
"laravel/framework": "5.8.*",
"spatie/laravel-permission": "^2.9",
"spatie/laravel-server-side-rendering": "^1.1",
"spiritix/lada-cache": "^3.0"

**Even I am getting the same result after updating the package.**

**Comment by spiritix** [comment]
Sorry, I can't provide support for legacy versions of Lada Cache. Please upgrade your Laravel version.
