### ISSUE TITLE
Question regarding this library

### ISSUE THREAD

**Issue by logan-jobzmall** [spiritix/lada-cache#113]
In the docs it says `Don't try to only have specific models including the Lada Cache trait, it will result in unexpected behavior. In the configuration, you will find the possibility to include or exclude specific models.`

This makes sense, however, what about third party models/traits that create relationships off the current models? Will these also cause the same issues? It would make sense that it would. How is this handled?

**Comment by spiritix** [comment]
Hi @logan-jobzmall. Third-party models are generally not affected or cached by Lada Cache, since they don't include the necessary trait. This is not a problem, as long as they remain part of encapsulated and decoupled third-party libraries.
