### ISSUE TITLE
auto-clear cache failure in production

### ISSUE THREAD

**Issue by liangguohuan** [spiritix/lada-cache#123]
discovery：
i guess the auto-clear cache function will fail when cache data is more and more large, it works fine because of the cache data is small  in test environment, but it often fail becuase of the cache data is large in production environment. It causes a lot of troubles for application, there is a better way to do so, please consider optimize this.

**Comment by spiritix** [comment]
Can you provide any details? Why do you think it fails?

**Comment by liangguohuan** [comment]
It's just my guess, i test it many times, and it works fine in test  env, but it sometimes fail in production env, i must force to flush all cache at that time. it confuses me, and i check the redis specific table tags size, maybe this is the reason?

**Comment by MGA-Kontainer** [comment]
Might be related to https://github.com/spiritix/lada-cache/pull/127

**Comment by spiritix** [comment]
This issue will be fixed in Lada Cache 6.0, the current release I'm working on. I've rewritten the library from scratch and added support for Laravel 12 and PHP 8.3. The new version is currently on master branch and being tested, expect a stable release in a few days.
