### ISSUE TITLE
Find a way to override Laravel's query builder

### ISSUE THREAD

**Issue by spiritix** [spiritix/lada-cache#14]
At the moment it is hardcoded in Illuminate\Database\Eloquent\Model::newBaseQueryBuilder. 
If we could find a way to override it, the model class would not be required anymore.

**Comment by Swanty** [comment]
One way to not require the model is to create a trait which would override the newBaseQueryBuilder.

Though it would require to put
`use LadaCacheTrait;`
inside every model class

**Comment by spiritix** [comment]
That doesn't change much, then you would still be required to touch all models.
I am currently working on it: https://github.com/spiritix/lada-cache/tree/17-override-query-builder
The "magic" happens here: https://github.com/spiritix/lada-cache/blob/17-override-query-builder/composer.json#L33

However, it does not work. :)

**Comment by Swanty** [comment]
Perhaps check this http://antecedent.github.io/patchwork/

**Comment by Swanty** [comment]
Hi.

Could you please release version 1.2.2 with the QueryBuilder.php fixes?

**Comment by spiritix** [comment]
Sure, done. 
I think I found a way to override the query builder, but this has low priority at the moment since it is basically working without it.

**Comment by spiritix** [comment]
May be solved by putting [this](https://github.com/spiritix/lada-cache/blob/17-override-query-builder/composer.json#L33) in the composer.json of the main project and not in the one of the Lada Cache library
