### ISSUE TITLE
Invalidation on row level does only work if primary key columns are named "id"

### ISSUE THREAD

**Issue by spiritix** [spiritix/lada-cache#16]
See here https://github.com/spiritix/lada-cache/blob/master/src/Spiritix/LadaCache/Reflector.php#L50-L57

**Comment by fede91it** [comment]
Is this in roadmap?

**Comment by spiritix** [comment]
Not really. It appears to me that giving primary keys any other name than `id` is a very rare case. What is your use case for that?

**Comment by spiritix** [comment]
Fixed in current release.
