### ISSUE TITLE
Possibility to only cache specific models

### ISSUE THREAD

**Issue by spiritix** [spiritix/lada-cache#2]
Not working at the moment.

It would result in all models getting cached but not invalidated properly. This is because the class who writes values in the cache doesn't know which models are extending the cache model.

Also I am not sure what would happen if you join a model that is cached from a model which is not cached.

**Comment by schealex** [comment]
is this related to lada-cache invalidating all cache if only one model of a specific class gets changed? if so this would be a very great enhancement! as if i recall correctly at the moment if you have like elo model article and you list all, all get cached, if you change article id 1 every article gets removed from cache.
thats greatly reducing the impact of caching if you have like 1000 articles and only update one and every article needs to be refetched from database.
idealy the change to the article would be directly written to the cache of that article id on sql update but i guess thats a bit more complicated.

**Comment by spiritix** [comment]
No, what you are speaking about is cache granularity on row level. That is already implemented and (mostly) working. This issue is a feature request, it should be possible to enable cache for specific models only and not just for all models or completely disabled.

**Comment by schealex** [comment]
how would that work than if thats already (mostly) working? if i update let's say User with ID 1 lada goes forward and invalidates cache for ALL Users. Souldn't it cache each row with it's id and invalidate only the updated/changed/deleted one?

**Comment by spiritix** [comment]
No, it invalidates only items containing data of user with ID 1. Lets say for example:

- Item 1 contains the result of the query "SELECT * FROM users WHERE id = 1" 
- Item 2 contains the result of the query "SELECT * FROM users WHERE id = 2"
- Item 3 contains the result of the query "SELECT * FROM users" 

Now you execute the following query: "DELETE FROM users WHERE id = 1" 

This will delete item 2 and 3, but not item 1. 
Great isn' it? ;)

**Comment by schealex** [comment]
wait what? lolz
shouldn't it be "This will delete item 1, but not item 2 and 3." ?! oO

**Comment by spiritix** [comment]
Ehm yes sure ;)

**Comment by spiritix** [comment]
Done, will be available in > v.1.1.
