### ISSUE TITLE
1.2 version has issue with Model::firstOrNew

### ISSUE THREAD

**Issue by Swanty** [spiritix/lada-cache#21]
In the new 1.2 version there seems to be a problem with Model::firstOrNew function which somehow bypasses the lada-cache QueryModel

>  [Symfony\Component\Debug\Exception\FatalThrowableError]
>   Type error: Argument 4 passed to Spiritix\LadaCache\Database\QueryBuilder::__construct() must be an instance of Spiritix\LadaCache\QueryHandler, none given, called in /home/vagrant/www/panacea/vendor/l
>   aravel/framework/src/Illuminate/Database/Query/Builder.php on line 2070

**Comment by spiritix** [comment]
override the following method in Spiritix\LadaCache\Database\QueryBuilder:

    public function newQuery()
    {
        return new static($this->connection, $this->grammar, $this->processor);
    }

the IDE doesn't find usages of a class if they are set up like this...
