### ISSUE TITLE
i get BadMethodCallException  when i disable lada 

### ISSUE THREAD

**Issue by mikimaine** [spiritix/lada-cache#24]
when i dont want lada 
i run the artisan command to disable it  and it told me 
Cache disabled
but when i changed to file cache this appears
BadMethodCallException in Repository.php line 367: 
This cache store does not support tagging.

**Comment by spiritix** [comment]
Will fix in the next release cycle. PR welcome.

**Comment by spiritix** [comment]
Can't reproduce. Please provide more information like stack trace, environment, etc.
Lada Cache doesn't make use of Laravel's Cache facade, it uses the Redis facade directly. Therefore I can't imagine that it's related to changing the cache driver.
