### ISSUE TITLE
ServiceProvider class_exists Error for DebugBar

### ISSUE THREAD

**Issue by 19peaches** [spiritix/lada-cache#26]
In the service provider on line 57:

```
if (class_exists('Barryvdh\\Debugbar\\LaravelDebugbar')) {
    $this->registerDebugbarCollector();
}
```

This throws major errors if you have DebugBar installed but not enabled.

I had to create my own provider and check the container for debugbar:

```
if ($this->app->offsetExists('debugbar')) {
    $this->registerDebugbarCollector();
}
```

would be a much better solution.

Or simply make `registerDebugbarCollector()` public so it can be overloaded.

**Comment by spiritix** [comment]
Thank you for this suggestion, will update the code
