### ISSUE TITLE
Cache Invalidation not working in Eloquent Relationship belongsToMany

### ISSUE THREAD

**Issue by george1974** [spiritix/lada-cache#30]
I have observed that though Lada-cache works for the most part, when it comes to eloquent relationships, the cache invalidation doesn't seem to work as expected.

For example:
$this->belongsToMany('App\Models\TableClass1','TableClass2','table_class1_id','table_class2_id');

The above relationship is cached properly during all the read operations for TableClass1, but if any row of TableClass1 or TableClass2 is modified, it purges the cache for the subsequent relationship for all rows of TableClass1/2. 
 
The problem is very much similar to as reported in Issue #11 ( Just that this time its related to eloquent relationship).

**Comment by spiritix** [comment]
Thanks for reporting, I will have a look at it in the next release cycle.

**Comment by george1974** [comment]
Thanks for the update. I have tried the same with hasMany and hasOne eloquent relationship and the bug is present in both cases. 
Looking forward to the next release.

**Comment by spiritix** [comment]
Fixed
