### ISSUE TITLE
Laravel 5.4

### ISSUE THREAD

**Issue by pushamaku** [spiritix/lada-cache#42]
Just tried to install with 5.4, and getting this error from composer require:

```
...
> php artisan optimize

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to undefined method Illuminate\Foundation\Application::share()

Script php artisan optimize handling the post-update-cmd event returned with error code 1
```
Does lada-cache support 5.4?

**Comment by spiritix** [comment]
Honestly, I had no time to test it so far. But thanks for the reminder, need to do that ASAP.

**Comment by pushamaku** [comment]
Thanks, that would be great! 👍

**Comment by Cracken6** [comment]
Hi. Just came across same problem. Could you fix it?

**Comment by spiritix** [comment]
Hi guys, please excuse my late reply. Since someone was so kind to create a PR for 5.4 support (https://github.com/spiritix/lada-cache/pull/44), I'll wait until the tests are passing and release a new version with it then.

**Comment by spiritix** [comment]
A new release supporting 5.4 will be published today. Sorry for the delay guys.
