### ISSUE TITLE
Any plans on making it work with Lumen

### ISSUE THREAD

**Issue by bhargav3** [spiritix/lada-cache#43]
I have built a read-only API that does heavy database querying and would like to use this project. I tried to install and it failed at `vendor:publish` with the following error.

I'm asking this with the an anticipation that it requires less work to support Lumen. If not, that's fine, let me know. Thanks!

````
php artisan vendor:publish
PHP Fatal error:  Call to undefined method Laravel\Lumen\Application::share() in /Users/bhargav/Projects/myfyba/api/vendor/spiritix/lada-cache/src/Spiritix/LadaCache/LadaCacheServiceProvider.php on line 138

Fatal error: Call to undefined method Laravel\Lumen\Application::share() in /Users/bhargav/Projects/myfyba/api/vendor/spiritix/lada-cache/src/Spiritix/LadaCache/LadaCacheServiceProvider.php on line 138

                                                               
  [Symfony\Component\Debug\Exception\FatalErrorException]      
  Call to undefined method Laravel\Lumen\Application::share() 
````

**Comment by Swanty** [comment]
See issue #42
lada-cache is not yet supported on laravel 5.4
try lumen 5.3

**Comment by bhargav3** [comment]
Thanks @Swanty My project's Lumen version is `5.3.*` but it still failed. I guess we will have to wait for the update.

**Comment by bhargav3** [comment]
@Swanty Thanks! It worked with Lumen 5.3 but had to install vendor publish command https://packagist.org/packages/laravelista/lumen-vendor-publish

But it won't be possible to disable or enable, so cache will always be enabled (as by the default)

I ended up not using for my project since mine is a read-only API and the write operations are done by my Laravel project, cache was not invalidated for changes.

Thanks for your suggestion and it helped.

**Comment by bhargav3** [comment]
I tried to install lada-cache for Lumen 5.4 and I notice two issues

- Call to undefined method Laravel\Lumen\Application::share()

> This can be solved by refactoring, replace `share` with `singleton`

- there are no commands defined in the "config" namespace.

> Need to import `config` command from Laravel

Please let me know if there are any plans to support Lumen 5.4

**Comment by spiritix** [comment]
Definitely, as soon as I find the time I will update it to support 5.4 Sorry for the delay. More about this here:
https://github.com/spiritix/lada-cache/issues/42
