### ISSUE TITLE
Caching relations

### ISSUE THREAD

**Issue by george-kar** [spiritix/lada-cache#50]
I have a model (table) **companies**

id _(index key)_, companyname, address, phone

I also have a model (table) **categories**

id _(index key)_, category

this relation is many to many, companies may have many categories and one category may have many companies. For that reason I created a table **companies_categories**

id_company _(index key)_, id_category _(index key)_

My question is if lada cache with the current logic will cache everything included the relation with row invalidation? As you see I have assigned both tables with primary key "id" but the relation table has no "id" and I am not sure how this will work.

**Comment by spiritix** [comment]
Thanks for your question. Actually, you are right, invalidation on row level will not work for the example you provided. Lada Cache will automatically fall back to invalidation on table level. In order for this to be working, #16 must be solved first. Important is that this will not cause bugs, it will simply invalidate more data than actually required.

**Comment by george-kar** [comment]
@spiritix thank you for your prompt reply. So, as I understand lada cache will work good caching everything including relation but every time a single-row change will be made to tables or in the relation table, lada cache will cache everything from scratch. Is that right?

At last, do you have any plans fixing #16 issue? Any eta? Can somehow people donate you to help on this?

**Comment by spiritix** [comment]
Yes, exactly. Every time you perform a change on one of these three tables, all queries querying the corresponding table will be invalidated. That's basically how the built-in MySQL query cache works regarding invalidation. 

I am planning to look at #16 and #46 within the next 1-2 months, but can't promise anything since I am pretty busy here at work. I really appreciate your intention to help me on this, however, it would help me the most if you could contribute to this project and create a pull request for this.

**Comment by george-kar** [comment]
I guess it wont be difficult to support dynamic primary key but it would be trouble when the table has more than one id. In such cases it will require major code changes.

Btw, in my example if on the middle table **companies_categories** I will add a primary key id:

id _(index key)_, id_company, id_category

would that solve the problem to allow row invalidation?

**Comment by spiritix** [comment]
Yes, adding an 'id' column on pivot tables should solve the problem. I think for comprehensively solving this issue #46 should be done first, because this issue also requires data from Eloquent.

**Comment by george-kar** [comment]
Hello again,

is there any way to know for specific calls if data retrieved by cache or database? Also, after an update or delete how can I know if the row invalidation worked or it recreated the whole cache?

**Comment by spiritix** [comment]
Yes, there is :) You need to install the DebugBar for Laravel, then there will be a 'Lada' tab which shows all actions done by the cache. Also, you will see if a query actually gets cached or not since cached queries disappear from the queries tab. https://github.com/barryvdh/laravel-debugbar

**Comment by george-kar** [comment]
I am not using debugbar, I switched to clockwork due to the fact that takes spaces from my app, while clockwork installs on chrome inspector. I already reinstalled it and I can see the lada tab with all information. But I didn't tested on row invalidation, that info would be also included on that tab?

**Comment by spiritix** [comment]
The information is included but not very obvious. It will tell you which tags have been invalidated. Therefore, first of all, you need to check which tags your query has. And from the name of the tags, it's also apparent if a row-level invalidation was executed or not.
