### ISSUE TITLE
caching logged in  user

### ISSUE THREAD

**Issue by george-kar** [spiritix/lada-cache#53]
Would it be possible to use lada to cache the logged in user to avoid reading the database on every request? As lada doesn't support it out of the box, I am using this plugin https://github.com/hobbiot/cacheable-auth-user but I was wondering if I can use lada for this as well.

**Comment by spiritix** [comment]
Lada Cache does per default cache all models, including the user model. As long as you are including the trait in all your models I don't see a reason why the user model shouldn't not be cached. Maybe you could check if the Auth Facade does internally use Eloquent, otherwise it won't work at all.
