### ISSUE TITLE
Cache not clearing

### ISSUE THREAD

**Issue by nicgutierrez** [spiritix/lada-cache#56]
Hey,

Great package, thanks for releasing and maintaining this.

I currently have a problem that I just noticed, it was fine until a few hours ago.

The cache on my website doesn't get cleared when new "items" get added to the database. It doesn't happen with every model, just with a particular one.

It's quite odd to describe and it works just fine on my local env.

Here's a URL in case you want to see it: https://insegreto.com/it/fresh

In that page you'll find a list of posts. New posts are not visible until I manually clear the cache but  you can see new comments right away.

I know the info is not much, but maybe you have already an idea of what's happening? Or maybe you can recommend a way to debug this?

--- EDIT
More info. I'm using Envoyer to manage my deployments and after re-deploying (same code) everything is working as expected. I would expect though to have the same issue again in a few hours. Will keep posted.

--- EDIT #2 
So.. after 6 hours, here we go again. Same issue. This time, re-deploying didn't fix the issue. I had to run `php artisan lada-cache:flush`.

**Comment by nicgutierrez** [comment]
Hey @spiritix, I'd like to debug this, is there any tips you or suggestions you can give me?

Cheers,
Nic

**Comment by spiritix** [comment]
Hi there,
In order to properly debug this, we need to figure out which query should trigger an invalidation but doesn't do so.
Please install [Laravel Debugbar](https://github.com/barryvdh/laravel-debugbar), you'll then see a tab 'Lada' in the Debugbar with all queries, tags, and types.
Once you figured out the plain SQL of both, the SELECT and the INSERT/UPDATE query, please post them here, ideally together with the corresponding PHP code.
Thanks

**Comment by nicgutierrez** [comment]
So, these are the plain SQLs for SELECT

`[Hit] select * from `secret` where `locale` = ? order by `created_at` desc limit 10 (1.93ms)`
`[Hit] select * from `users` where `users`.`id` = ? limit 1 (1.17ms)`

These are some of the invalidation queries:

**removing:**
`[Invalidation (delete)] delete from `favorites` where `favourable_type` is null and `favourable_id` = ? (3.79ms)`
`[Invalidation (delete)] delete from `secret` where `id` = ? (2.01ms)`

**updating:**
`[Invalidation (update)] update `users` set `points` = ?, `updated_at` = ? where `id` = ? (1.96ms)`
`[Invalidation (update)] update `secret` set `votes` = ?, `votes_up` = ?, `ranking` = ?, `controversy` = ?, `confidence` = ?, `updated_at` = ? where `id` = ? (1.59ms)`

**Comment by spiritix** [comment]
So which model is the one which does return the outdated results? Users?

**Comment by nicgutierrez** [comment]
I know for sure that Secrets doesn't return the updated set.

**Comment by spiritix** [comment]
Ok, the queries for Secret look pretty normal, I don't really see a reason why they should not be invalidated.
I'll need to further investigate that.
Please provide the following information:
- PHP Code (Eloquent) in which you assemble the queries
- Tags and parameters for both the SELECT and UPDATE/INSERT/DELETE query (click on the row in Lada tab in Debugbar)

**Comment by nicgutierrez** [comment]
Ok, here you go:

**Eloquent:**
```php
$secrets = Secret::where('locale', App::getLocale())->orderBy('ranking', 'DESC')->paginate($perPage);
```

**Tags and parameters**
![screen shot 2017-12-22 at 10 51 24](https://user-images.githubusercontent.com/436432/34295604-257b5984-e706-11e7-93ef-31fb160c01d4.png)

**Comment by spiritix** [comment]
Thanks. As far as can see, all tags seem to be correct. Please post the same information for the INSERT/UPDATE/DELETE queries as well.

**Comment by nicgutierrez** [comment]
Hey @spiritix 

thanks for getting back. I'm currently stuck with some other projects, I'll get back to you with the info you asked for.

Cheers,
Nic

**Comment by nicgutierrez** [comment]
Hi @spiritix 

We are planning to use this package here at PS but I'm still concerned about this issue, that's why I spent a bit of time retrieving the queries you were asking for, here you go:

Everytime a new "secret" is created these are the queries:

```sql
insert into `secret` (`message`, `age`, `gender`, `category_id`, `locale`, `is_active`, `ip`, `user_id`, `updated_at`, `created_at`) values ('ladacache insert test .. ', '18', '1', '3', 'it', '1', '127.0.0.1', '1', '2018-02-05 10:16:33', '2018-02-05 10:16:33')
```

```sql
select count(*) as aggregate from `favorites` where `favorites`.`favourable_id` = '1494968' and `favorites`.`favourable_id` is not null and `favorites`.`favourable_type` = 'App\Models\Secret' and `user_id` = '1'
```

```sql
update `secret` set `code` = 'bvYRWyXyLa', `updated_at` = '2018-02-05 10:16:33' where `id` = '1494968'
```

During a normal session, a user could trigger several updates by upvoting or downvoting:

```sql
select * from `secret` where `secret`.`id` = '1494968' limit 1
```

```sql
update `secret` set `votes` = '1', `votes_up` = '1', `ranking` = '8528.7597778', `controversy` = '1', `confidence` = '0.37844750322521', `updated_at` = '2018-02-05 10:27:07' where `id` = '1494968'
```

I think that's everything?

Thanks again for looking into this.

Cheers,
Nic

**Comment by Swanty** [comment]
@nicgutierrez

Can you show PHP code for the queries?
It's not apparent from the sql queries whether query builder is being used or eloquent.

**Comment by nicgutierrez** [comment]
hey @Swanty 

I'm using Eloquent, here's an example:

```php
// simplified $data ->
$data = $request->all();

$secret = Secret::create($data);
$secret->code = \Hashids::encode($secret->id);
$secret->save();
```

**Comment by Swanty** [comment]
@nicgutierrez

That looks fine, hmm...

I'm curious what is the default "ranking" for "secret"? I see that on the listing you're ordering by "ranking" and also paginating.
Is it possible that the newly inserted "secret" has some weird "ranking" that makes it show up on the last page of the listing?

**Comment by nicgutierrez** [comment]
@Swanty 

The order by ranking is the "viral section", so I wouldn't expect a new item to appear under that section. Here's the code for the "latest"

```php
$secrets = Secret::where('locale', App::getLocale())->orderBy('created_at', 'DESC')->paginate($perPage);
```

This is also the section where I should see the new items and also the section where you notice the problem.

Thanks,
Nic

**Comment by spiritix** [comment]
Looking at your queries, I don't see a reason why they should not work.
Let's recap, the following query:

```
$secrets = Secret::where('locale', App::getLocale())->orderBy('ranking', 'DESC')->paginate($perPage);
```

Does return outdated results after this insert:

```
$secret = Secret::create($data);
$secret->code = \Hashids::encode($secret->id);
$secret->save();
```

Is that correct?
As we saw in your screenshot above, the SELECT query has the following tag:

```
tags:database:insegreto:table_unspecific:secret
```

Now the question is if the INSERT query does get the same tags or not. Please share a screenshot of the Debugbar with all details for the INSERT query.

 I just tried to replicate the error on my machine using your queries but wasn't able to do so. Does the problem reproduce consistently or only occasionally?

**Comment by nicgutierrez** [comment]
It doesn't return outdated results after the update. At that point, everything is still working fine.

The error is "random" but after that point it will be consistent and all the queries will return outdated content. It's like if it gets stuck and doesn't invalidate the cache so it will always return records that are X hours old, depending on when the "random" error occurred.

In addition to what we said, the errors happens only on my production environment. I never had any problems locally. 

Here are the screenshots for Insert/Update (these two happen one after the other) and an extra update that will happen when a user decides to upvote a "secret".

![screen shot 2018-02-06 at 15 50 31](https://user-images.githubusercontent.com/436432/35869019-11da2c10-0b56-11e8-937b-fa17a1f65611.png)
![screen shot 2018-02-06 at 15 50 52](https://user-images.githubusercontent.com/436432/35869020-11f54dba-0b56-11e8-9cfb-10691bf94223.png)
![screen shot 2018-02-06 at 15 50 21](https://user-images.githubusercontent.com/436432/35869021-120c050a-0b56-11e8-95e6-e1169c2b40dd.png)

Thanks again for your help

**Comment by spiritix** [comment]
At all this seems like either a race condition or a problem caused by a third-party library in connection with Lada Cache. Unfortunately, I wasn't able to reproduce it, neither with Unit tests nor with manual testing, not even when using the queries you posted. It seems like the only thing you can do is the following:

1. Wait until the problem occurs
2. Manually check the tags of the not-updated item in cache
3. Manually check the tags of the next write query (which doesn't invalidate the item even though it should)

Now if the tags don't match, we know that under certain circumstances the Tagger isn't able to properly generate them. Therefore put the following code in Tagger.php after line 112:

```
        if ($this->reflector->getSql() === "...query.." && !in_array($tags, '..missing tag..')) {
            debug_print_backtrace();
            die();
        }
```

If the tags do match, the problem must be in the invalidation. Therefore put a similar statement in Invalidator.php around line 57.

Please feel free to re-open the issue, as soon as you've figured out anything. Other than this I am really not able to help you, I am sorry.

**Comment by nicgutierrez** [comment]
hey @spiritix 

The issue is happening only on prod, with every model, so not just the queries I provided with, so I will have a look and see if I can add the code on production as you suggested. If I can get more info, I will re-open :)

Thanks again for your help!
