### ISSUE TITLE
Question: Nested queries with dynamic whereHas & where 

### ISSUE THREAD

**Issue by madsem** [spiritix/lada-cache#61]
Hey,

thanks a lot for making this awesome package.

I'm playing around with it and it seems to do everything I need, but wanted to ask if will reliably cache nested queries like the following (If I add primary keys named ID to all pivot tables):

Would this create different cached versions for the below query based on the dynamic variables, or would the dynamic parts invalidate the cache every time a visitor hits my site from another country, OS, device type etc.
```php
return $this->domain->load([
                    'advertisers' => function ($q) {
                        $q->with([
                            $this->adsRelationship => function ($q) {
                                $q->whereHas('countries', function ($q) {
                                    $q->whereIn('key', [session('country_code'), 'XX']);
                                })
                                  ->whereHas('operatingSystems', function ($q) {
                                      $q->whereIn('key', [session('os'), 'all']);
                                  })
                                  ->whereHas('deviceTypes', function ($q) {
                                      $q->whereIn('key', [session('device_type'), 'all']);
                                  })
                                  ->whereHas('browsers', function ($q) {
                                      $q->whereIn('key', [session('browser'), 'all']);
                                  })
                                  ->when($this->adType == 'images', function ($q) {
                                      $q->with([
                                          'cpaBanners' => function ($q) {
                                              $q->whereHas('adSize', function ($q) {
                                                  $q->where('size', '=',
                                                      $this->width . 'x' . $this->height);
                                              });
                                          }
                                      ]);
                                  })
                                  ->when($this->adType == 'contextuals', function ($q) {
                                      $q->whereHas('adSize', function ($q) {
                                          $q->where('size', '=',
                                              $this->width . 'x' . $this->height);
                                      });
                                  })
                                  ->when($this->adType == 'urls', function ($q) {
                                      $q->doesnthave('cpaBanners');
                                  })
                                  ->when($this->adType == 'snippets', function ($q) {
                                      $q->doesnthave('adSize');
                                  });
                            }
                        ]);
                    }
                ]);
```

Also, am I correct that once Installing Lada, I should remove all calls to "Cache::remember()" in my controllers for it to work as intended?

Thank you! :) 👍

**Comment by spiritix** [comment]
Thanks, glad to see that this library is helpful. 

The purpose of Lada Cache is to reliably cache all kind of queries, including nested ones, as long as you consider the limitations mentioned [here](https://github.com/spiritix/lada-cache#known-issues-and-limitations).
Still, as it's impossible to test all constellations and combinations of queries, I would recommend you to test if your query gets properly invalidated. You can easily do that by executing a write query after it, for example:

```
$advertiser = Advertiser::findOrFail(1);
$advertiser->name = 'Test';
$advertiser->save();
```

Now execute the mentioned SELECT query again and see if the new name is included in the results.
Lada Cache does hash the query itself as well as all query parameters, therefore using a different country or OS in your example will lead to a different cache item being used.

Regarding your second question:
Yes, please remove all `Cache::remember()` ocurrences, Lada Cache doesn't invalidate them.

**Comment by madsem** [comment]
@spiritix thanks a lot for this detailed answer!

I had also discovered that actually a new Tab in the Laravel Debugbar appears that shows me hits and misses. Very easy to use and so far it seems it caches everything exactly as you describe.

Again, thanks a lot for creating this and also maintaining. Very awesome, you rock!

**Comment by spiritix** [comment]
Exactly, debug bar should give you all information you need, even for debugging. Cheers!
