### ISSUE TITLE
Eloquent paginate is ignored and pages display the same results

### ISSUE THREAD

**Issue by madsem** [spiritix/lada-cache#63]
Sorry for opening all these issues haha, but it seems to be a bug.

```php
$domains = Domain::orderBy('updated_at', 'desc')
                         ->paginate(10);
```

Got any solution for this? I checked the issues but couldn't find pagination problems.

Results (table has 30 unique domain names):
![screen shot 2018-04-19 at 4 36 04 pm](https://user-images.githubusercontent.com/3166991/38998437-db42b686-43ef-11e8-9e71-0fdc67cebcc7.png)
![screen shot 2018-04-19 at 4 36 14 pm](https://user-images.githubusercontent.com/3166991/38998438-db5d8c0e-43ef-11e8-85f8-ec808a3e9b2e.png)
![screen shot 2018-04-19 at 4 36 22 pm](https://user-images.githubusercontent.com/3166991/38998439-db75eb6e-43ef-11e8-9b0a-0811806dfc15.png)

![screen shot 2018-04-19 at 4 38 50 pm](https://user-images.githubusercontent.com/3166991/38998606-34ca21d0-43f0-11e8-8548-ddb0ccfd8529.png)

**Comment by spiritix** [comment]
No worries, we all profit from bugs being fixed. Your queries look just fine, it did properly cache them. How are the queries changing if you navigate trough the pages?

**Comment by madsem** [comment]
It seems that the mistake is on my end and because of the orderBy(), if I remove it the pagination works but when I add it back I see the same issue also with Lada cache removed...

Not sure why this is happening as I have no other cache installed and flushed redis manually, removed compiled and cleared cache / view cache.

But most likely this has nothing to do with lada cache, so I'm closing it for now.

Thanks :)
