### ISSUE TITLE
Lada fails to function properly when there is a Redis prefix key set

### ISSUE THREAD

**Issue by KnightAR** [spiritix/lada-cache#77]
I was trying to debug why the tests were failing consistently so I can create a pull requests for a fix I was creating for Lada, and while looking at the failing tests, I've discovered that Lada fails to function properly when a Redis key prefix is set in the database.redis.options.prefix config variable. After I set the variable to false, all the tests pass. I have created a pull request to fix the tests, however, the prefix issue (which seems to not be set by default in normal laravel environments but is in the default testing config) still exists and needs to be fixed properly to support installs with a redis prefix.

Here is my Travis-CLI pass with the tests updated: https://travis-ci.org/KnightAR/lada-cache/builds/611542124

Here is the PR to fix the tests with the database.redis.options.prefix config change: https://github.com/spiritix/lada-cache/pull/76

**Comment by spiritix** [comment]
Thanks, merged!
