### ISSUE TITLE
Tests fail on Travis CI due to missing Redis class

### ISSUE THREAD

**Issue by spiritix** [spiritix/lada-cache#85]
Sometimes all tests involving Redis are failing on Travis CI:

> Error: Class 'Redis' not found

I am not able to consistently reproduce it though, sometimes it works, sometimes it doesn't. Would appreciate if someone could look into that.

**Comment by savornicesei** [comment]
Hi @spiritix,
I had the same error when running the tests on my machine. Fixed it by installing phpredis (the php7-redis package in openSUSE Tumbleweed repo).
I suppose adding predis/predis to the dev requirements in composer.json would also work.

Best,
Simo

**Comment by spiritix** [comment]
Actually that should not be required since we already require the `redis-server` service. I think it's a bug in Travis CI, sometimes it works, sometimes it doesn't. Anyway, your fix seems to solve the issue, so I am merging this. Thanks for your contribution.
