### ISSUE TITLE
Have some question.

### ISSUE THREAD

**Issue by ethaizone** [spiritix/lada-cache#9]
**Why Lada Cache require php 5.6?**
Laravel 5.2 require php 5.5.9 so I think if Lada Cache can require same php as laravel. It's will make another people can use this library easier.

**Do you have plan to make it as traits?**
I think traits is better more than extend class and user can use it easier.

**Comment by spiritix** [comment]
> Why Lada Cache require php 5.6?
For legacy reasons. Is not required anymore, will change it in the next release.

> Do you have plan to make it as traits?
No, but starting with the next version neither extending a class nor including a trait will be required anymore. It will just work out of the box!
