### ISSUE TITLE
 Call to undefined function config_path()

### ISSUE THREAD

**Issue by Wolffyx** [spiritix/lada-cache#90]
Hello,

 I installed the library on my project and I got this(see below) error. 

` Call to undefined function Spiritix\LadaCache\config_path()` 

My project uses Lumen ^6.x and to fix the problem I modified `LadaCacheServiceProvider.php` on line 43 `config_path(PATH)->config(PATH)` and `Command.php` at line 32.

But now I get:
` There are no commands defined in the "vendor" namespace.`

Regards

**Comment by spiritix** [comment]
This project is not (yet) tested with Lumen. Added a separate issue https://github.com/spiritix/lada-cache/issues/92
