### ISSUE TITLE
Lada breaks Laravel Telescope

### ISSUE THREAD

**Issue by genesiscz** [spiritix/lada-cache#91]
So Lada creates a QueryBuilder here: https://github.com/spiritix/lada-cache/blob/master/src/Spiritix/LadaCache/Database/Connection.php#L31

But doesn't pass the fifth required argument, a model. Could this be an optional model? I guess telescope somehow uses this function and breaks because it tries to create a new instance of QueryBuilder without the Model.

**Comment by spiritix** [comment]
Which version of Laravel are you using?

**Comment by genesiscz** [comment]
Laravel             "version": "v7.4.0",
Telescope   "version": "v3.2.0",

**Comment by genesiscz** [comment]
Simply making the fifth parameter optional ( = null)  seems to fix this issue for me. I am not sure if it doesn't break something, but since everything in Telescope works, I suppose it doesnt.

**Comment by spiritix** [comment]
Thanks for providing the fix. It seems working, I merged it and will publish a bug fix release in a few moments.

**Comment by genesiscz** [comment]
Actually this broken a lot. Can you revert the commit and try to fix it more thoroughly? 


  {
            "file": "\/data\...\/vendor\/spiritix\/lada-cache\/src\/Spiritix\/LadaCache\/Tagger.php",
            "line": 87,
            "function": "getRows",
            "class": "Spiritix\\LadaCache\\Reflector",
            "type": "->"
        },

**Comment by genesiscz** [comment]
Probably relationships 

 ```
$instanceZones = Zone::where([
            "instance_id" => $instance_id,
            ["left", "<", $points->minLng],
            ["right", ">", $points->maxLng],
            ["bottom", "<", $points->minLat],
            ["top", ">", $points->maxLat],
        ])->with("zonePoints", "carrierZones", "storeZones")->get();
```

**Comment by spiritix** [comment]
Reverted the fix. It's actually weird how a default value for a previously required parameter can break something. Needs further investigation.

**Comment by genesiscz** [comment]
I forgot to said that if I manually assign a new App\Model\User in the constructor (when having the fifth parameter to null), it starts to work.

**Comment by genesiscz** [comment]
@spiritix will you have some time to look at this in  a near future or should I investigate more? I am not sure about the dependencies and process and I wouldn't like to break it again considering there are no tests to try it on

**Comment by spiritix** [comment]
Not in the next weeks, can't promise anything. I will reopen the issue, maybe somebody else wants to have a look at it. Otherwise, I'll try to have a look as soon as possible.

**Comment by spiritix** [comment]
Should be fixed with the latest release
