### ISSUE TITLE
cleanBindings() must be of the type array, null given, whereHas > whereIn() issue?

### ISSUE THREAD

**Issue by hendryb** [spiritix/lada-cache#97]
Got this error
`Argument 1 passed to Illuminate\Database\Query\Builder::cleanBindings() must be of the type array, null given, called in ...\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php on line 870`

on this line: UserController.php
```
...
        $users = User::whereHas("user_documents", function($q) use($request) {
            $q->whereIn("name", $request->names);
        });
...
```

User.php
```
...
    public function user_documents()
    {
        return $this->hasMany(UserDocument::class);
    }
...
```

I guess it has something to do with whereHas() > whereIn() ?

**Comment by hendryb** [comment]
When i switch to 

```
$users = User::whereHas("user_documents", function($q) use($request) {
            $q->where("name", $request->names);
        });
```

it gives a different error:
`Argument 1 passed to Spiritix\LadaCache\Reflector::getTablesFromWhere() must be an instance of Spiritix\LadaCache\Database\QueryBuilder, instance of Illuminate\Database\Query\Builder given, called in ...\vendor\spiritix\lada-cache\src\Spiritix\LadaCache\Reflector.php on line 145`

**Comment by spiritix** [comment]
Are you sure that **all** your models include the LadaCacheTrait?

`use \Spiritix\LadaCache\Database\LadaCacheTrait;`

**Comment by hendryb** [comment]
@spiritix Thank you for your comment, i double checked everything, and just one more error like the above came back. It have something to do with the model "Role" i use from https://github.com/spatie/laravel-permission any chance i can include LadaCacheTrait inside an existing vendor's Model? There the Trait isnt added yet.

**Comment by spiritix** [comment]
Create a custom "Role" model which extends the one from the third-party package and include the trait there. Or if that doesn't work, you will have to fork the package.
