### ISSUE TITLE
Cache not refreshed for relations when using updateOrCreate()

### ISSUE THREAD

**Issue by hendryb** [spiritix/lada-cache#98]
I am getting old data after i updated some details. These are my files:

UserInfo.php
```
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class UserInfo extends Model
{
    protected $guarded = [];

    use \Spiritix\LadaCache\Database\LadaCacheTrait;

}
```

User.php
```
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use \Spiritix\LadaCache\Database\LadaCacheTrait;

    protected $guarded = [];

    protected $with = ['user_info'];

    public function user_info()
    {
        return $this->hasOne(UserInfo::class);
    }
}
```

```
$user = User::find(1);
echo $user->user_info->first_name // outputs 'test1';
```

then i tried to update his first_name like this:

UserService.php
```
$user_info = $user->user_info()->updateOrCreate(['user_id' => 1], [
	'first_name' => 'test2'
]);
```

then it results in this:
```
$user = User::find(1);
echo $user->user_info->first_name // outputs 'test1';
```

what is the issue here?

**Comment by hendryb** [comment]
So i have excluded LadaCacheTrait from UserInfo and it started working again. But now this Model doesn't get cached.

**Comment by spiritix** [comment]
If you want to exclude certain tables, please do so using the provided configuration option: https://github.com/spiritix/lada-cache/blob/master/config/lada-cache.php#L76
The trait should always be included in all models, otherwise it might result in bugs.

Regarding the issue you mentioned initially, was the data actually updated in the database? Is the proper data returned once you truncated the cache?

**Comment by hendryb** [comment]
i included the Trait again, but whenever i update the field, the cache didnt get refreshed.

it starts like this:
$user->user_info()->first_name = test1

i update like this:
```
$user_info = $user->user_info()->updateOrCreate(['user_id' => 1], [
	'first_name' => 'test2'
]);
```

When i now echo $user->user_info()->first_name it still says test1, and in the database i have test2. So it got updated all fine, but not in the cache

**Comment by spiritix** [comment]
No, it should not be like this :) For further debugging I would need to see the output of the [Debugbar](https://github.com/barryvdh/laravel-debugbar), specifically of the Queries tab and the Lada tab.

**Comment by hendryb** [comment]
For some odd reason it started acting normal again. If it happens again, i report here. How can i share the debugbar info with you?

**Comment by hendryb** [comment]
Okay, another one, 

I have 2 models: 
- **User**
```
class User extends Authenticatable
{

	// ...
    use \Spiritix\LadaCache\Database\LadaCacheTrait;
	
    public function notifications()
    {
        return $this->hasMany(Notification::class);
    }
	
	// ...
}
```
- **Notification**
```
class Notification extends Model
{
    use \Spiritix\LadaCache\Database\LadaCacheTrait;
	// ...

    public function user()
    {
        return $this->belongsTo(User::class);
    }
	
	// ...
}
```

For testing i used this code:
```
    foreach(auth()->user()->notifications as $notification){        
        if(!$notification->read_at){
            echo $notification->id.'<br />';
        }
        if($notification->id==2203){
            $notification->read_at = Carbon::now();
            $notification->save();
        }
    }
```
But Cache is not getting updated. I keep getting notification id 2203.

see screenshots:
![11-ladaNotificationsHit](https://user-images.githubusercontent.com/22586660/89519100-231b7380-d7dc-11ea-98e2-d5b247236647.jpg)

![11-withUpdateSaveNotificationQuery](https://user-images.githubusercontent.com/22586660/89519104-244ca080-d7dc-11ea-8f21-706b700b2b10.jpg)

![11-withUpdateSaveNotificationQueryAgain](https://user-images.githubusercontent.com/22586660/89519097-231b7380-d7dc-11ea-838c-92c69dff034f.jpg)

![11-phpMyAdmin](https://user-images.githubusercontent.com/22586660/89519096-21ea4680-d7dc-11ea-8cac-ae3190e8e0c8.jpg)
